
config = loadjson('config.json');
reslice_nii(config.t1, ...
            config.outname, ...
            config.outres, ...
            true, true, 2)
        
% reslice usage:
% reslice_nii(old_fn, ...
%             new_fn, ...
%             [voxel_size], ...
%             [verbose], .... 
%             [bg], ...
%             [method], [img_idx], [preferredForm]);

