  
function main1(t1)
    disp(['Parameter t1: ', t1]);
    % Aquí puedes poner el resto de tu código

% Cargar el archivo de configuración
config = loadjson('config.json.example');


reslice_nii(config.t1, ...
            config.outname, ...
            config.outres, ...
            true, true, 2);
        
% Uso de reslice:
% reslice_nii(old_fn, ...
%             new_fn, ...
%             [voxel_size], ...
%             [verbose], .... 
%             [bg], ...
%             [method], [img_idx], [preferredForm]);



end
 
